import { expect, test } from "@playwright/test";

test("YOLOE UI reports missing service, missing GPU and unprepared models", async ({ page }) => {
  await page.route("http://127.0.0.1:8766/**", (route) => route.abort());
  await page.goto("/index.html");
  await page.locator("#taskInferenceBtn").click();
  await page.locator("#inferenceYoloeModeBtn").click();
  await expect(page.locator("#onnxInferenceControls")).toBeHidden();
  await page.locator("#connectYoloeBtn").click();
  await expect(page.locator("#yoloeRunStatus")).toContainText("npm run yoloe:start");
  await expect(page.locator("#previewYoloeBtn")).toBeDisabled();
  await page.unroute("http://127.0.0.1:8766/**");
  await page.route("http://127.0.0.1:8766/**", (route) => route.fulfill({ json: { version: 1, cuda: false, gpu: null, models: [], busy: false } }));
  await page.locator("#connectYoloeBtn").click();
  await expect(page.locator("#yoloeBackendBadge")).toHaveText("GPU unavailable");
  await expect(page.locator("#registerYoloeExamplesBtn")).toBeDisabled();
  await page.unroute("http://127.0.0.1:8766/**");
  await page.route("http://127.0.0.1:8766/**", (route) => route.fulfill({ json: { version: 1, cuda: true, gpu: "Test GPU", models: [], busy: false } }));
  await page.locator("#connectYoloeBtn").click();
  await expect(page.locator("#yoloeRunStatus")).toContainText("npm run yoloe:prepare");
  await expect(page.locator("#registerYoloeExamplesBtn")).toBeDisabled();
  await page.locator("#inferenceOnnxModeBtn").click();
  await expect(page.locator("#selectInferenceModelBtn")).toBeVisible();
  await page.locator("#inferenceYoloeModeBtn").click();
  await page.unroute("http://127.0.0.1:8766/**");
  await page.route("http://127.0.0.1:8766/status", async (route) => { await new Promise((resolve) => setTimeout(resolve, 1500)); await route.abort(); });
  await page.locator("#connectYoloeBtn").click();
  await page.locator("#cancelActiveOperationBtn").click();
  await expect(page.locator("#yoloeRunStatus")).toContainText("stopped");
  await expect(page.locator("#yoloeBackendBadge")).toHaveText("Disconnected");
  await expect(page.locator("#connectYoloeBtn")).toBeEnabled();
});

test("YOLOE visual targets preview without mutation, save mapped classes, cancel and retain source labels", async ({ page }) => {
  test.setTimeout(60_000);
  const requests: Record<string, unknown>[] = [];
  await page.route("http://127.0.0.1:8766/**", async (route) => {
    const url = route.request().url();
    const request = route.request().method() === "POST" ? route.request().postDataJSON() : {};
    requests.push(request);
    if (url.endsWith("/status")) return route.fulfill({ json: { version: 1, cuda: true, gpu: "Test GPU", models: ["yoloe-26s-seg"], busy: false } });
    if (url.endsWith("/prepare")) return route.fulfill({ json: { id: "profile-1", model: "yoloe-26s-seg", classes: { "0": "Light / White" }, exampleCount: 1, referenceSha256: "reference", gpu: "Test GPU" } });
    return route.fulfill({ json: { detections: [{ classId: 0, confidence: 0.9, left: 20, top: 20, right: 80, bottom: 80 }] } });
  });
  await page.goto("/index.html");
  await page.locator("#emptyLoadSampleBtn").click();
  await expect(page.locator("#workspaceStandbyPanel")).toBeHidden({ timeout: 30_000 });
  const count = () => page.evaluate(() => Reflect.get(window, "__easyLabelingTestApi")?.getRectCount?.() ?? -1);
  await expect.poll(count).toBe(52);
  await page.locator("#taskInferenceBtn").click();
  await page.locator("#inferenceYoloeModeBtn").click();
  await page.locator("#connectYoloeBtn").click();
  await page.evaluate(() => Reflect.get(window, "__easyLabelingTestApi")?.selectRectsByIndex?.([0]));
  await page.locator("#registerYoloeExamplesBtn").click();
  await expect(page.locator("#yoloeExampleList > div")).toHaveCount(1);
  await page.locator("#previewYoloeBtn").click();
  await expect(page.locator("#yoloeRunStatus")).toContainText("Preview · 1 detection(s)");
  await expect(page.locator("#yoloePreviewCanvas")).toBeVisible();
  await expect.poll(count).toBe(52);
  await expect(page.locator("#labelSourceSelect option")).toHaveCount(1);
  await page.locator("#yoloeProfileName").fill("parts_v1");
  await expect(page.locator("#yoloePreviewCanvas")).toBeHidden();
  await page.locator("#saveYoloeCurrentBtn").click();
  await expect(page.locator("#yoloeRunStatus")).toContainText("inference-yoloe-26s-seg-parts_v1");
  await expect.poll(count).toBe(1);
  await page.locator("#labelSourceSelect").selectOption("0");
  await expect.poll(count).toBe(52);
  await page.locator("#yoloeConfidenceInput").fill("1.1");
  await page.locator("#previewYoloeBtn").click();
  await expect(page.locator("#yoloeRunStatus")).toContainText("between 0 and 1");
  await page.locator("#yoloeConfidenceInput").fill("0.25");
  // Cancellation uses the existing operation overlay and must not save a preview.
  await page.unroute("http://127.0.0.1:8766/**");
  await page.route("http://127.0.0.1:8766/infer", async (route) => { await new Promise((resolve) => setTimeout(resolve, 1500)); await route.abort(); });
  await page.locator("#previewYoloeBtn").click();
  await page.locator("#cancelActiveOperationBtn").click();
  await expect(page.locator("#yoloeRunStatus")).toContainText("stopped");
  await expect.poll(count).toBe(52);
  expect(requests.some((request) => request.profileId === "profile-1")).toBe(true);
});
